apiVersion: v1
kind: Service
metadata:
  name: echoserver-service
spec:
  type: LoadBalancer
  clusterIP: 10.96.0.12
  selector:
    app: echoserver
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 3000
status:
  loadBalancer:
    ingress:
      - ip: 192.0.2.127
